### PR TITLE
feat(safari-extension): add Safari Web Extension POC reusing browser-extension-core

### PR DESCRIPTION
**Pull request by FagnerMartinsBrack**
## What

A proof-of-concept **Safari Web Extension** (`projects/extensions/safari-extension`) that behaves like the existing Chrome and Firefox extensions and reuses [`browser-extension-core`](../tree/main/projects/browser-extension-core) for all of its logic. Safari Web Extensions speak the same WebExtension APIs as Chrome/Firefox, so this is a thin browser shell over the shared core — exactly how the other two extensions consume it.

## Why a sibling project (not an `experiments/` POC)

The iOS POC lives in `experiments/` because iOS forced a native Swift rewrite that couldn't reuse the JS core. Safari is different: it runs the **same** web-extension code, so the way to "reuse as much as possible of `browser-extension-core`" is to make it a sibling of `chrome-extension`/`firefox-extension`.

## What's reused vs. Safari-specific

Everything substantive comes from the core; this project is just the per-browser shell:

| Reused from `browser-extension-core` | Safari shell (this PR) |
|--------------------------------------|------------------------|
| OAuth 2.0 + PKCE, token refresh | `manifest.json` (MV2) |
| Siren reading-list client | `runtime/background/*.browser.ts` glue |
| Popup helpers (filter, paginate, avatar, relative-time) | `runtime/popup/popup.browser.ts` glue |
| `installShortcuts` / `isCmdD` | `runtime/content/shortcut.browser.ts` glue |
| `popup.styles.css` + popup markup | `runtime/browser.d.ts` API typings |
| `initBuildExtension` (esbuild build) | `scripts/build-extension.js` wiring |

The shell mirrors the **Firefox** extension (Manifest V2, native `browser` namespace, `OffscreenCanvas` icon tinting in the background page) rather than Chrome, because Safari does not implement Chrome's MV3 `offscreen` API. Context menus use the de-duplicating `create-context-menus` module (with a unit test) since Safari's `"persistent": false` background page can be unloaded and re-run, just like a Chrome MV3 service worker.

To avoid any **server change**, the POC reuses the already-registered `hutch-chrome-extension` OAuth client (its `https://readplace.com/oauth/callback` redirect is shared by all extensions) — matching the iOS POC.

## Verification

- ✅ `safari-extension:compile` produces a complete, loadable MV2 web-extension bundle (manifest + bundled JS + popup + shared CSS + icons; server URL baked in via esbuild `define`).
- ✅ `safari-extension:check` passes: tsc, biome, knip, unused-CSS, the `create-context-menus` unit test, and **100% coverage**.
- ✅ Full-repo `pnpm check` is green with this addition (the one transient `save-link:check` failure under parallel load is a pre-existing flake — nx flagged it as flaky, and it passes in isolation).
- ✅ `pnpm install --frozen-lockfile` is consistent; the lockfile diff is only the new importer.

## Scope / Mac-only steps (intentionally out of CI)

Unlike the Chrome/Firefox extensions, this POC has **no** Pulumi infra, auto-update hosting, or store-publishing workflow. Wrapping the bundle into a Safari app (`xcrun safari-web-extension-converter`, via `pnpm --filter safari-extension wrap`) and Safari E2E (`safaridriver`) both require **macOS**, so they're kept out of the Linux CI `check` path and documented in the project README — the same way the iOS POC documents its Mac-only steps.

## How to try it (on a Mac)

```sh
pnpm --filter safari-extension compile   # build dist-extension-compiled/
pnpm --filter safari-extension wrap      # generate the Xcode project
open dist-safari-app/Readplace/Readplace.xcodeproj   # Run, then enable in Safari → Settings → Extensions
```

https://claude.ai/code/session_01C963qNBMT53HWSU8zr7RU6

---
_Generated by [Claude Code](https://claude.ai/code/session_01C963qNBMT53HWSU8zr7RU6)_

### CODE REVIEW

**Comment by FagnerMartinsBrack** [comment]
@claude Review this PR. Use your Read tool to read the local file `.github/workflows/claude-PR-code-reviewer.md` for instructions. The file is in the checked-out repository.

## Context
- **Repo**: Readplace/readplace.com
- **PR**: #498
- **Commit**: 826d7fe2f18b6e6e1c8dee49a395c16ec0c91717

**Comment by FagnerMartinsBrack** [comment]
@claude address all low prio issues

**Comment by FagnerMartinsBrack** [comment]
@claude Review this PR. Use your Read tool to read the local file `.github/workflows/claude-PR-code-reviewer.md` for instructions. The file is in the checked-out repository.

## Context
- **Repo**: Readplace/readplace.com
- **PR**: #498
- **Commit**: 4957513534c5f6ae3f3bac7db511b3133dead35e

**Comment by FagnerMartinsBrack** [comment]
Rebased this branch onto the latest `main` (29 new commits).

- **No merge conflicts.** My commit only adds files under `projects/extensions/safari-extension/` plus a `pnpm-lock.yaml` importer block, so git's 3-way merge applied cleanly; `pnpm install --frozen-lockfile` confirms the lockfile is consistent.
- **Preserved the review-applied commit.** `--force-with-lease` caught that `4957513` (the `claude[bot]` "clarify OAuth client reuse" commit) had landed after my last fetch — I cherry-picked it back on top, so nothing was lost. The branch is now `main` → POC commit → clarification commit.
- **Green:** full `pnpm check` passes after the rebase, and `safari-extension:check` is at 100% coverage.

The force-push was purely this rebase.

---
_Generated by [Claude Code](https://claude.ai/code)_

**Comment by FagnerMartinsBrack** [comment]
@claude Review this PR. Use your Read tool to read the local file `.github/workflows/claude-PR-code-reviewer.md` for instructions. The file is in the checked-out repository.

## Context
- **Repo**: Readplace/readplace.com
- **PR**: #498
- **Commit**: ca7ac6f3aa2f0087f623357c24e601c110c4a0c8

**Comment by FagnerMartinsBrack** [comment]
Rebased onto the latest `main` (17 new commits) and re-reviewed the PR end-to-end.

**Rebase:** no git conflicts (the PR only adds files plus a lockfile importer block); `pnpm install --frozen-lockfile` stays consistent.

**Functional drift found and fixed.** Two `main` commits evolved the chrome/firefox shells this POC mirrors, so the Safari shell was stale even though nothing conflicted textually:

- `1c3362f` (real save milestones): core's CSS no longer has the `--starting` class the old popup relied on — the Safari progress bar would never have animated. Ported the `initSaveProgress`/`initSaveProgressSequencer` wiring, the background's `save-progress` broadcasts, and the tab-pinned capture (`tabId` rides the save so the saved icon lands on the right tab).
- `6f41fb3` (PDF binary upload): ported the one-line content-script change (`isPdfViewerDocument` → empty `rawHtml` on native PDF tabs so the binary upload path kicks in). Safari gets firefox's variant; the extra embedder-shell fingerprint is Chrome-specific.

After the port, the Safari background/content/popup are byte-identical to firefox's apart from the deliberate divergences (`contextMenus` namespace + de-duplicating menu init, shared OAuth client id, comment wording). README's save-flow bullet updated to match.

**Review result:** Siren contract untouched (all API access via the core walker), `create-context-menus` keeps DI/`init*` conventions, every `setIcon` path is `.catch`-guarded in core so Safari quirks degrade to the default icon. `safari-extension:check` green at 100% coverage; full-repo `pnpm check` green (exit 0, all 26 projects).

---
_Generated by [Claude Code](https://claude.ai/code)_

**Comment by FagnerMartinsBrack** [comment]
@claude Review this PR. Use your Read tool to read the local file `.github/workflows/claude-PR-code-reviewer.md` for instructions. The file is in the checked-out repository.

## Context
- **Repo**: Readplace/readplace.com
- **PR**: #498
- **Commit**: 55130a4bfef4c082a32607c9642fe1a2be5aeb65

**Comment by FagnerMartinsBrack** [comment]
@claude CI has FAILED. Use your Read tool to read the local file `.github/workflows/claude-PR-CI-failure-fixer.md` for instructions. The file is in the checked-out repository.

## Context
- **Attempt**: 1 of 5
- **Run ID**: 27863971413
- **PR**: #498
- **Branch**: claude/vigilant-edison-iHMpb

## Failed Jobs
- web-tests: Run pnpm install --frozen-lockfile --reporter=append-only --loglevel=warn

**Comment by FagnerMartinsBrack** [comment]
This POC has shown a safari extension is easier than I thought, very little Safari-specific due to the dsign of browser-core. Nice POC but closing as it's not a priority right now (prioritising iOS app instead so you can share a link from any browser to Readplace)
